# Generated by Django 3.0.6 on 2020-05-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='updated_at',
            new_name='uploaded_at',
        ),
    ]
