# Generated by Django 3.0.6 on 2020-05-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200522_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
