# Generated by Django 3.0.6 on 2020-05-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200522_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
